services:
  web:
    image: "${IMAGE}"
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eventum.rule=Host(`api.merup.ru`)"
      - "traefik.http.routers.eventum.entrypoints=websecure"
      - "traefik.http.routers.eventum.tls=true"
      - "traefik.http.services.eventum.loadbalancer.server.port=8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
