# Generated by Django 5.1.7 on 2025-04-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tags', to='app.eventum')),
            ],
            options={
                'unique_together': {('eventum', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tags', to='app.eventum')),
            ],
            options={
                'unique_together': {('eventum', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.eventum')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_groups', to='app.eventum')),
                ('participants', models.ManyToManyField(related_name='groups', to='app.participant')),
                ('tags', models.ManyToManyField(blank=True, related_name='groups', to='app.grouptag')),
            ],
            options={
                'unique_together': {('eventum', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='app.eventtag')),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.eventum')),
                ('participants', models.ManyToManyField(blank=True, related_name='individual_events', to='app.participant')),
                ('groups', models.ManyToManyField(blank=True, related_name='events', to='app.participantgroup')),
            ],
        ),
    ]
