# Generated by Django 5.1.7 on 2025-04-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventum')),
            ],
            options={
                'unique_together': {('slug', 'eventum')},
            },
        ),
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventum')),
            ],
            options={
                'unique_together': {('slug', 'eventum')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventum')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventum')),
                ('tags', models.ManyToManyField(blank=True, to='app.grouptag')),
                ('participants', models.ManyToManyField(blank=True, to='app.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tags', models.ManyToManyField(blank=True, to='app.eventtag')),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventum')),
                ('groups', models.ManyToManyField(blank=True, to='app.group')),
                ('participants', models.ManyToManyField(blank=True, to='app.participant')),
            ],
        ),
    ]
