# Generated by Django 5.1.7 on 2025-09-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventum',
            name='password_hash',
        ),
    ]
