# Generated by Django 5.1.7 on 2025-09-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
