# Generated by Django 5.1.7 on 2025-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='temp', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
