# Generated by Django 5.1.7 on 2025-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True),
        ),
    ]
