# Generated by Django 5.1.7 on 2025-09-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_avatar_url_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
