# Generated by Django 5.1.7 on 2025-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_participantgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grouptag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
