# Generated by Django 5.1.7 on 2025-09-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_eventtag_slug_alter_grouptag_slug'),
    ]

    operations = [
        # Добавляем индексы для улучшения производительности запросов
        migrations.RunSQL(
            # Создаем индексы
            """
            CREATE INDEX IF NOT EXISTS idx_participantgroup_eventum 
            ON app_participantgroup (eventum_id);
            
            CREATE INDEX IF NOT EXISTS idx_participant_eventum 
            ON app_participant (eventum_id);
            
            CREATE INDEX IF NOT EXISTS idx_grouptag_eventum 
            ON app_grouptag (eventum_id);
            
            CREATE INDEX IF NOT EXISTS idx_eventtag_eventum 
            ON app_eventtag (eventum_id);
            
            CREATE INDEX IF NOT EXISTS idx_event_eventum 
            ON app_event (eventum_id);
            
            CREATE INDEX IF NOT EXISTS idx_userrole_user_eventum 
            ON app_userrole (user_id, eventum_id);
            """,
            # Откат миграции
            """
            DROP INDEX IF EXISTS idx_participantgroup_eventum;
            DROP INDEX IF EXISTS idx_participant_eventum;
            DROP INDEX IF EXISTS idx_grouptag_eventum;
            DROP INDEX IF EXISTS idx_eventtag_eventum;
            DROP INDEX IF EXISTS idx_event_eventum;
            DROP INDEX IF EXISTS idx_userrole_user_eventum;
            """
        ),
    ]
