# Generated by Django 5.1.7 on 2025-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_participant_user_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventum',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
