# Generated by Django 5.1.7 on 2025-09-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_eventum_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('kind', models.CharField(choices=[('venue', 'Площадка/Территория'), ('building', 'Здание/Корпус'), ('room', 'Аудитория/Кабинет/Зал'), ('area', 'Зона/Фойе/Outdoor'), ('other', 'Другое')], default='room', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.eventum')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'unique_together': {('eventum', 'slug')},
            },
        ),
    ]
