# Generated by Django 5.1.7 on 2025-09-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='app.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(choices=[('venue', 'Площадка/Территория'), ('building', 'Здание/Корпус'), ('room', 'Аудитория/Кабинет'), ('area', 'Зона/Outdoor'), ('other', 'Другое')], default='room', max_length=20),
        ),
    ]
