# Generated by Django 5.1.7 on 2025-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_location_alter_location_kind'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['eventum'], name='app_partici_eventum_1c7f98_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='app_partici_user_id_cb959d_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['name'], name='app_partici_name_1fdcdd_idx'),
        ),
    ]
