# Generated by Django 5.1.7 on 2025-09-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_participant_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grouptag',
            index=models.Index(fields=['eventum'], name='app_groupta_eventum_7a7607_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptag',
            index=models.Index(fields=['name'], name='app_groupta_name_2e534a_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroup',
            index=models.Index(fields=['eventum'], name='app_partici_eventum_dde549_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroup',
            index=models.Index(fields=['name'], name='app_partici_name_963edd_idx'),
        ),
    ]
