# Generated by Django 5.1.7 on 2025-09-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_group_tag_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='app.grouptag'),
        ),
    ]
