# Generated by Django 5.1.7 on 2025-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_event_group_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL изображения для события'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text="Максимальное количество участников (используется только при типе 'По записи')", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_type',
            field=models.CharField(choices=[('all', 'Для всех'), ('registration', 'По записи'), ('manual', 'Вручную')], default='all', help_text='Тип определения участников для мероприятия', max_length=20),
        ),
    ]
