# Generated by Django 5.1.7 on 2025-09-30 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_change_event_location_to_many_to_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='app.participant')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'indexes': [models.Index(fields=['participant'], name='app_eventre_partici_2c39ea_idx'), models.Index(fields=['event'], name='app_eventre_event_i_fe9279_idx'), models.Index(fields=['registered_at'], name='app_eventre_registe_b0cfc9_idx')],
                'unique_together': {('participant', 'event')},
            },
        ),
        migrations.CreateModel(
            name='EventWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название волны мероприятий', max_length=200)),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_waves', to='app.eventum')),
                ('tag', models.OneToOneField(help_text='Тег, связанный с волной (1 к 1)', on_delete=django.db.models.deletion.CASCADE, related_name='event_wave', to='app.eventtag')),
            ],
            options={
                'verbose_name': 'Event Wave',
                'verbose_name_plural': 'Event Waves',
                'indexes': [models.Index(fields=['eventum'], name='app_eventwa_eventum_05cc41_idx'), models.Index(fields=['name'], name='app_eventwa_name_9024fd_idx')],
                'unique_together': {('eventum', 'name')},
            },
        ),
    ]
