# Generated by Django 5.1.7 on 2025-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_event_wave_and_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwave',
            name='blacklist_group_tags',
            field=models.ManyToManyField(blank=True, help_text='Теги групп участников, которые НЕ могут записываться на волну', related_name='blacklisted_waves', to='app.grouptag'),
        ),
        migrations.AddField(
            model_name='eventwave',
            name='blacklist_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы участников, которые НЕ могут записываться на волну', related_name='blacklisted_waves', to='app.participantgroup'),
        ),
        migrations.AddField(
            model_name='eventwave',
            name='whitelist_group_tags',
            field=models.ManyToManyField(blank=True, help_text='Теги групп участников, которые могут записываться на волну (если пуст - доступны все теги)', related_name='whitelisted_waves', to='app.grouptag'),
        ),
        migrations.AddField(
            model_name='eventwave',
            name='whitelist_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы участников, которые могут записываться на волну (если пуст - доступны все группы)', related_name='whitelisted_waves', to='app.participantgroup'),
        ),
    ]
