# Generated by Django 5.1.7 on 2025-10-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_eventwave_blacklist_group_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventum',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL изображения для eventum'),
        ),
    ]
