# Generated by Django 5.1.7 on 2025-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_add_image_url_to_eventum'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventum',
            name='registration_open',
            field=models.BooleanField(default=True, help_text='Открыта ли регистрация на мероприятия'),
        ),
    ]
