# Generated by Django 5.1.7 on 2025-11-01 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_registration_open_to_eventum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGroupV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_event_group', models.BooleanField(default=False, help_text='Если True, группа используется для связи с событиями и не показывается в основном интерфейсе')),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_groups_v2', to='app.eventum')),
            ],
            options={
                'verbose_name': 'Participant Group V2',
                'verbose_name_plural': 'Participant Groups V2',
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroupV2EventRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_v2_relations', to='app.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_relations', to='app.participantgroupv2')),
            ],
            options={
                'verbose_name': 'Participant Group V2 Event Relation',
                'verbose_name_plural': 'Participant Group V2 Event Relations',
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroupV2GroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('inclusive', 'Включает (целевая группа входит в исходную)'), ('exclusive', 'Исключает (целевая группа НЕ входит в исходную)')], default='inclusive', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='app.participantgroupv2')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='app.participantgroupv2')),
            ],
            options={
                'verbose_name': 'Participant Group V2 Group Relation',
                'verbose_name_plural': 'Participant Group V2 Group Relations',
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroupV2ParticipantRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('inclusive', 'Включает (участник входит в группу)'), ('exclusive', 'Исключает (участник НЕ входит в группу)')], default='inclusive', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_relations', to='app.participantgroupv2')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_v2_relations', to='app.participant')),
            ],
            options={
                'verbose_name': 'Participant Group V2 Participant Relation',
                'verbose_name_plural': 'Participant Group V2 Participant Relations',
            },
        ),
        migrations.AddIndex(
            model_name='participantgroupv2',
            index=models.Index(fields=['eventum'], name='app_partici_eventum_874c90_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroupv2',
            index=models.Index(fields=['is_event_group'], name='app_partici_is_even_5dbab5_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroupv2eventrelation',
            index=models.Index(fields=['group'], name='app_partici_group_i_d41f86_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroupv2eventrelation',
            index=models.Index(fields=['event'], name='app_partici_event_i_de0a95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantgroupv2eventrelation',
            unique_together={('group', 'event')},
        ),
        migrations.AddIndex(
            model_name='participantgroupv2grouprelation',
            index=models.Index(fields=['group'], name='app_partici_group_i_02d75f_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroupv2grouprelation',
            index=models.Index(fields=['target_group'], name='app_partici_target__7c99f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantgroupv2grouprelation',
            unique_together={('group', 'target_group')},
        ),
        migrations.AddIndex(
            model_name='participantgroupv2participantrelation',
            index=models.Index(fields=['group'], name='app_partici_group_i_ea9e94_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgroupv2participantrelation',
            index=models.Index(fields=['participant'], name='app_partici_partici_18dd0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantgroupv2participantrelation',
            unique_together={('group', 'participant')},
        ),
    ]
