# Generated by Django 5.1.7 on 2025-11-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_add_event_group_v2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='app_eventre_partici_2c39ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='app_eventre_registe_b0cfc9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        # Data migration: purge old participant-based registrations to avoid
        # conflicts when making event one-to-one. The new schema is per-event
        # configuration, so old rows are not needed.
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('app', 'EventRegistration').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='allowed_group',
            field=models.ForeignKey(blank=True, help_text='Группа участников, которым доступна запись на это мероприятие. Если не указана, доступна всем участникам eventum.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='app.participantgroupv2'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='applicants',
            field=models.ManyToManyField(blank=True, help_text="Участники, подавшие заявки (используется при типе 'application')", related_name='event_applications', to='app.participant'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников, которое может попасть на мероприятие через регистрацию', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_type',
            field=models.CharField(choices=[('button', 'Запись по кнопке'), ('application', 'По заявкам')], default='button', help_text="Тип добавления участников: 'button' - сразу попадают в группу, 'application' - сохраняются заявки", max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.OneToOneField(help_text='Одно мероприятие может иметь только одну настройку регистрации', on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='app.event'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['allowed_group'], name='app_eventre_allowed_fb296e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registration_type'], name='app_eventre_registr_44f174_idx'),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='registered_at',
        ),
    ]
