# Generated by Django 5.1.7 on 2025-11-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_change_event_registration_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventwave',
            name='blacklist_group_tags',
        ),
        migrations.RemoveField(
            model_name='eventwave',
            name='blacklist_groups',
        ),
        migrations.RemoveField(
            model_name='eventwave',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='eventwave',
            name='whitelist_group_tags',
        ),
        migrations.RemoveField(
            model_name='eventwave',
            name='whitelist_groups',
        ),
        migrations.AddField(
            model_name='eventwave',
            name='registrations',
            field=models.ManyToManyField(blank=True, help_text='Регистрации на мероприятия, входящие в эту волну', related_name='waves', to='app.eventregistration'),
        ),
    ]
