# Generated by Django 5.1.7 on 2025-11-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_refactor_event_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_applications', to='app.participant')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.eventregistration')),
            ],
            options={
                'verbose_name': 'Event Registration Application',
                'verbose_name_plural': 'Event Registration Applications',
                'indexes': [models.Index(fields=['registration'], name='app_eventre_registr_bf147e_idx'), models.Index(fields=['participant'], name='app_eventre_partici_48766d_idx'), models.Index(fields=['applied_at'], name='app_eventre_applied_104842_idx')],
                'unique_together': {('registration', 'participant')},
            },
        ),
    ]
