# Generated by Django 5.1.7 on 2025-11-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_add_schedule_visible_to_eventum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников', null=True),
        ),
    ]
