# Generated by Django 5.1.7 on 2025-11-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_participant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
    ]
