# Generated by Django 5.1.7 on 2025-11-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_max_participants_from_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group_tags',
        ),
        migrations.RemoveField(
            model_name='participantgroup',
            name='tags',
        ),
        migrations.DeleteModel(
            name='GroupTag',
        ),
    ]
