# Generated by Django 5.1.7 on 2025-11-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_event_group_tags_remove_participantgroup_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='groups',
        ),
        migrations.DeleteModel(
            name='ParticipantGroup',
        ),
    ]
