# Generated by Django 5.1.7 on 2025-11-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_old_participant_groups'),
    ]

    operations = [
        # Переименование таблиц: убираем префикс v2
        migrations.RunSQL(
            # Переименование основной таблицы групп
            sql="ALTER TABLE app_participantgroupv2 RENAME TO app_participantgroup;",
            reverse_sql="ALTER TABLE app_participantgroup RENAME TO app_participantgroupv2;",
        ),
        migrations.RunSQL(
            # Переименование таблицы связей группа-участник
            sql="ALTER TABLE app_participantgroupv2participantrelation RENAME TO app_participantgroupparticipantrelation;",
            reverse_sql="ALTER TABLE app_participantgroupparticipantrelation RENAME TO app_participantgroupv2participantrelation;",
        ),
        migrations.RunSQL(
            # Переименование таблицы связей группа-группа
            sql="ALTER TABLE app_participantgroupv2grouprelation RENAME TO app_participantgroupgrouprelation;",
            reverse_sql="ALTER TABLE app_participantgroupgrouprelation RENAME TO app_participantgroupv2grouprelation;",
        ),
        migrations.RunSQL(
            # Переименование таблицы связей группа-событие
            sql="ALTER TABLE app_participantgroupv2eventrelation RENAME TO app_participantgroupeventrelation;",
            reverse_sql="ALTER TABLE app_participantgroupeventrelation RENAME TO app_participantgroupv2eventrelation;",
        ),
    ]
