# Generated by Django 5.1.7 on 2025-11-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_participant_group_v2_tables'),
    ]

    operations = [
        # Переименование колонки event_group_v2_id в event_group_id в таблице app_event
        migrations.RunSQL(
            sql="ALTER TABLE app_event RENAME COLUMN event_group_v2_id TO event_group_id;",
            reverse_sql="ALTER TABLE app_event RENAME COLUMN event_group_id TO event_group_v2_id;",
        ),
    ]
