# Имя вашего workflow, будет отображаться в разделе "Actions" на GitHub
name: Build and Deploy to Yandex Cloud

# Триггеры для запуска:
# - при пуше в ветку main
# - позволяет запускать вручную из интерфейса GitHub
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Переменные окружения, доступные во всех задачах (jobs)
env:
  # Используем GitHub Container Registry (ghcr.io)
  REGISTRY: ghcr.io
  # Имя репозитория в формате 'владелец/имя_репозитория'
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Первая задача: сборка и публикация Docker-образа
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Выходные данные для передачи в следующую задачу
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      version: ${{ steps.meta.outputs.version }}

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Аутентификация в GitHub Container Registry (GHCR)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. (НОВЫЙ ШАГ) Настройка Docker Buildx
      # Этот шаг необходим для использования кэширования 'type=gha'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. (УЛУЧШЕНИЕ) Генерация метаданных (тегов и лейблов) для образа
      # Автоматически создает тег с коротким SHA и другие полезные теги
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 5. (ИСПРАВЛЕННЫЙ ШАГ) Сборка и отправка образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Указываем контекст сборки
          file: ./backend/Dockerfile # Явное указание Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Включаем кэширование, которое теперь будет работать
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Вторая задача: деплой в Yandex Cloud
  deploy:
    name: Deploy to Yandex Cloud
    # Эта задача зависит от успешного завершения задачи 'build'
    needs: build
    runs-on: ubuntu-latest
    
    # Указываем окружение, для которого выполняется деплой
    # Это позволяет использовать Environment-специфичные секреты и видеть историю деплоев в GitHub
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }} # Сюда можно подставить URL вашего приложения

    steps:
      # 1. Установка Yandex Cloud CLI (аналогично вашему скрипту)
      - name: Install Yandex Cloud CLI
        run: |
          sudo apt-get update && sudo apt-get install -y bash curl jq gettext
          curl --fail --silent --location --remote-name https://storage.yandexcloud.net/yandexcloud-yc/install.sh
          sudo bash install.sh -i /usr/local/yandex-cloud -n
          sudo ln -s /usr/local/yandex-cloud/bin/yc /usr/local/bin/yc

      # 2. Аутентификация в Yandex Cloud через сервисный аккаунт
      # Используем секрет, который вы добавите в настройках репозитория
      - name: Authenticate in Yandex Cloud
        run: |
          echo "${{ secrets.YC_SA_KEY_JSON }}" > key.json
          yc config profile create sa-profile
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      # 3. Деплой новой ревизии Serverless Container
      # Все переменные из GitLab CI заменены на секреты и переменные GitHub
      - name: Deploy new container revision
        id: deploy
        run: |
          yc serverless container revision deploy \
            --container-id ${{ secrets.YC_CONTAINER_ID }} \
            --image "${{ needs.build.outputs.tags }}" \
            --cores 4 \
            --memory 1024mb \
            --concurrency 1 \
            --execution-timeout 10s \
            --service-account-id ${{ secrets.YC_SERVICE_ACCOUNT_ID }} \
            --secret environment-variable=DB_NAME,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_NAME \
            --secret environment-variable=DB_HOST,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_HOST \
            --secret environment-variable=DB_PASSWORD,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_PASSWORD \
            --secret environment-variable=DB_USER,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_USER

