name: Build and Deploy to Yandex Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: eventum-backend

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - name: Set short git SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
      - name: Configure Kaniko auth
        run: |
          mkdir -p ${{ github.workspace }}/kaniko/.docker
          echo "${{ secrets.YC_SA_KEY_JSON }}" > ${{ github.workspace }}/key.json
          auth_val=$(echo -n "json_key:$(cat ${{ github.workspace }}/key.json)" | base64 | tr -d '\n')
          cat <<EOF > ${{ github.workspace }}/kaniko/.docker/config.json
          {"auths":{"cr.yandex":{"auth":"$auth_val"}}}
          EOF
      - name: Build and push image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/backend:/workspace \
            -v ${{ github.workspace }}/kaniko/.docker:/kaniko/.docker \
            gcr.io/kaniko-project/executor:latest \
            --context /workspace \
            --dockerfile /workspace/Dockerfile \
            --destination "cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}" \
            --custom-platform linux/amd64 \
            --cache=true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local/yandex-cloud -n
          sudo ln -s /usr/local/yandex-cloud/bin/yc /usr/local/bin/yc
      - name: Authenticate to Yandex Cloud
        run: |
          cat <<'EOF' > key.json
          ${{ secrets.YC_SA_KEY_JSON }}
          EOF
          yc config profile create sa-profile
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
      - name: Deploy container revision
        run: |
          yc serverless container revision deploy \
            --container-id ${{ secrets.YC_CONTAINER_ID }} \
            --image "cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.sha_short }}" \
            --cores 4 \
            --memory 1024mb \
            --concurrency 1 \
            --execution-timeout 10s \
            --service-account-id ${{ secrets.YC_SERVICE_ACCOUNT_ID }} \
            --secret environment-variable=DB_NAME,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_NAME \
            --secret environment-variable=DB_HOST,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_HOST \
            --secret environment-variable=DB_PASSWORD,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_PASSWORD \
            --secret environment-variable=DB_USER,id=e6qmac6cr2goqb03sfjn,version-id=e6qtom5dst8bamfc4pfh,key=DB_USER
